In [1]:
import numpy as np
#numpy.reshape(a, newshape, order='C')
#gives a new shape to an array without changing its data
#params a : array_like, Array to be reshaped
#       newshape: int or tuple of ints
#       The new shape should be compatible with the original shape.
#       If an integer, the result will be a 1-D array ot that lengths.
#       One shape dimension can be -1. In this case, the value is
#       inferred from the length of the array and remaining dimesions

In [2]:
a = np.zeros((10, 2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
b = a.T

In [4]:
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
# Taking a view makes it possible to modify the shape
# without modifying the initial object
c = b.view()

In [7]:
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
c.shape = (20)

AttributeError: incompatible shape for a non-contiguous array

In [12]:
a = np.arange(6).reshape((3, 2))

In [13]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [14]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [26]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [27]:
a.reshape(2, 3)
a

array([0, 1, 2, 3, 4, 5])

In [29]:
a = np.arange(6).reshape((3, 2))
a 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [30]:
a.reshape(-1)

array([0, 1, 2, 3, 4, 5])

In [32]:
a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
c = np.reshape(a, (2, 3))
c

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
a.T

array([[0, 2, 4],
       [1, 3, 5]])

In [20]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [33]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [35]:
np.reshape(a, 6, order = 'F')

array([1, 4, 2, 5, 3, 6])

In [36]:
np.reshape(a, (3, -1))   # the unspecified value is infered to be 2

array([[1, 2],
       [3, 4],
       [5, 6]])