In [1]:
import numpy as np
#numpy.c_
#translates slice objects to concatenation along second axis
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.c_.html
#Axes are defined for arrays with more than one dimesion.
#A 2-dimensionale array has two corresponding axes: the first
#running vertically downwards across rows(axis 0), and the second
#running horizontally across columns (axis 1)
#https://docs.scipy.org/doc/numpy-1.10.0/glossary.html

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a

array([1, 2, 3])

In [2]:
b

array([4, 5, 6])

In [4]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
c = np.array([[1, 2, 3]])
d = np.array([[4, 5, 6]])
np.c_[c, d]

array([[1, 2, 3, 4, 5, 6]])

In [7]:
np.c_[c, 0, 0, 1, 3, d]

array([[1, 2, 3, 0, 0, 1, 3, 4, 5, 6]])