In [1]:
#numpy.random.permutation
#Randomly permute a sequence, or return a permuted range.
#f x is a multi-dimensional array, it is only shuffled along its first index.
#https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.permutation.html
import numpy as np


In [2]:
#examples
np.random.permutation(10)

array([1, 2, 0, 9, 8, 6, 5, 4, 3, 7])

In [3]:
np.random.permutation([1, 4, 9, 12, 15])

array([ 1, 12,  4,  9, 15])

In [4]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr = np.arange(9).reshape(3, 3)
np.random.permutation(arr)

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [7]:
shuffled_indices = np.random.permutation(15)
shuffled_indices

array([ 4,  0,  5,  9, 12, 14, 13,  8,  2,  3,  7,  6, 10, 11,  1])

In [8]:
test_ratio = 0.25
test_set_size = int(len(shuffled_indices) * test_ratio)
test_set_size

3

In [9]:
len(shuffled_indices)

15

In [10]:
len(shuffled_indices) * test_ratio

3.75

In [11]:
test_indices = shuffled_indices[:test_set_size]
test_indices

array([4, 0, 5])

In [12]:
train_indices = shuffled_indices[test_set_size:]
train_indices

array([ 9, 12, 14, 13,  8,  2,  3,  7,  6, 10, 11,  1])

In [13]:
import pandas as pd
data = pd.DataFrame(["eins", "zwei", "drei", "vier", "funf", "sechs", "sieben", "ach", "neun", "zehn", "elf", "zwölf", "dreizehn", "vierzehn", "fünfzehn", "sechszehn", "siebzehn"])
data

0
0        eins
1        zwei
2        drei
3        vier
4        funf
5       sechs
6      sieben
7         ach
8        neun
9        zehn
10        elf
11      zwölf
12   dreizehn
13   vierzehn
14   fünfzehn
15  sechszehn
16   siebzehn

In [14]:

data.iloc[test_indices]

0
4   funf
0   eins
5  sechs

In [15]:
data.loc[test_indices]

0
4   funf
0   eins
5  sechs

In [23]:
identifier = 11
np.int64(identifier)

11

In [24]:
import hashlib
i64 = np.int64(identifier)
hash(i64)

11

In [27]:
hash(np.int64(identifier))

11

In [29]:
type(i64)

numpy.int64

In [33]:
hi64 = hashlib.md5(i64)
hi64
type(hi64)

_hashlib.HASH

In [42]:
dhi64 = hi64.digest()
dhi64

b'\x9eJ\x85r\x9fx\xb2\x97SY\xdb\x96\x8f\xd8\\\x01'

In [43]:
dhi64[-1]

1

In [44]:
dhi64[-1] < 256 * 0.25

True

In [45]:
type(dhi64)

bytes

In [46]:
tmp = [1, 2, 3, 4, 5, 6, 7]
type(tmp)

list

In [47]:
tmp[-1]

7

In [48]:
data.reset_index()

index          0
0       0       eins
1       1       zwei
2       2       drei
3       3       vier
4       4       funf
5       5      sechs
6       6     sieben
7       7        ach
8       8       neun
9       9       zehn
10     10        elf
11     11      zwölf
12     12   dreizehn
13     13   vierzehn
14     14   fünfzehn
15     15  sechszehn
16     16   siebzehn

In [49]:
indexed = data.reset_index()

In [50]:
indexed["index"]

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
Name: index, dtype: int64